# Local development: uses keyfile path from .env
# CI/CD: uses service account JSON from secrets

analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: analytics
      keyfile: "{{ env_var('GCP_SA_KEY_FILE') }}"
      threads: 4
      timeout_seconds: 300
